// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package: Package = .init(
    name: "Kazakusan",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "Kazakusan",
            targets: ["AppModule"],
            bundleIdentifier: "com.pookjw.Kazakusan",
            teamIdentifier: "P53D29U9LJ",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "../")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [],
            path: ".",
            plugins: [.plugin(name: "KazakusanCore", package: "KazakusanCore")]
        )
    ]
)
